# Uncomment this line to define a global platform for your project



target "UTCS" do

pod 'pop'
pod 'Tweaks'
pod 'Shimmer'
pod 'NMSSH'
pod "RQShineLabel"
pod 'DPMeterView'
pod 'MBProgressHUD'
pod "AFNetworking"
pod "JVFloatLabeledTextField", :git => 'https://github.com/jverdi/JVFloatLabeledTextField'
pod "PocketSVG", :git => "https://github.com/arielelkin/PocketSVG"

end

