target "UTCS" do
pod 'pop', :git => 'https://github.com/facebook/pop.git'
pod 'Tweaks'
pod 'Shimmer'
pod 'NMSSH'
pod "RQShineLabel"
pod 'DPMeterView'
pod 'MBProgressHUD'
pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage', '~> 2.0'
pod "JVFloatLabeledTextField"
pod "PocketSVG", :git => "https://github.com/arielelkin/PocketSVG"
pod "SwiftyJSON", :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
use_frameworks!

end

