language: objective-c

before_script:
- mv -v ./uMAD/Config.template.swift ./uMAD/Config.swift
- echo "echo \"Ran dummy fabricscript.sh\"" > ./scripts/fabricscript.sh
- echo ./scripts/fabricscript.sh
- chmod a+x ./scripts/fabricscript.sh

xcode_project: UTCS/UTCS.xcodeproj
xcode_scheme: UTCS
podfile: UTCS/Podfile
osx_image: xcode7.2

script:
- xctool  -workspace UTCS/UTCS.xcworkspace
  -scheme UTCS
  -sdk iphonesimulator 
  build
  CODE_SIGNING_REQUIRED=NO

email:
    on_failure: change
